-- SQL query to insert all provinces of Indonesia into the 'provinces' table.
-- The list includes all 38 official provinces as of the latest administrative divisions.

INSERT INTO `ticketmarketplace`.`provinces` (`name`) VALUES
('Aceh'),
('Bali'),
('Bangka Belitung Islands'),
('Banten'),
('Bengkulu'),
('Central Java'),
('Central Kalimantan'),
('Central Papua'),
('Central Sulawesi'),
('East Java'),
('East Kalimantan'),
('East Nusa Tenggara'),
('Gorontalo'),
('Highland Papua'),
('Jakarta'),
('Jambi'),
('Lampung'),
('Maluku'),
('North Kalimantan'),
('North Maluku'),
('North Sulawesi'),
('North Sumatra'),
('Papua'),
('Riau'),
('Riau Islands'),
('South Kalimantan'),
('South Papua'),
('South Sulawesi'),
('South Sumatra'),
('Southeast Sulawesi'),
('Southwest Papua'),
('West Java'),
('West Kalimantan'),
('West Nusa Tenggara'),
('West Papua'),
('West Sulawesi'),
('West Sumatra'),
('Special Region of Yogyakarta');
