/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FormUI;

/**
 *
 * @author Lenovo
 */
public class FormSellerFlashSale extends javax.swing.JFrame {

    /**
     * Creates new form FormSellerFlashSale
     */
    public FormSellerFlashSale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSetUp = new javax.swing.JButton();
        lblNamaEvent = new javax.swing.JLabel();
        lblHargaAwal = new javax.swing.JLabel();
        lblJumlahTicketFlashSale = new javax.swing.JLabel();
        lblTanggalMulai = new javax.swing.JLabel();
        lblTanggalSelesai = new javax.swing.JLabel();
        lblHargaDiskon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSetUp1 = new javax.swing.JButton();
        lblNamaEvent1 = new javax.swing.JLabel();
        lblHargaAwal1 = new javax.swing.JLabel();
        lblJumlahTicketFlashSale1 = new javax.swing.JLabel();
        lblTanggalMulai1 = new javax.swing.JLabel();
        lblTanggalSelesai1 = new javax.swing.JLabel();
        lblHargaDiskon1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSetUp2 = new javax.swing.JButton();
        lblNamaEvent2 = new javax.swing.JLabel();
        lblHargaAwal2 = new javax.swing.JLabel();
        lblJumlahTicketFlashSale2 = new javax.swing.JLabel();
        lblTanggalMulai2 = new javax.swing.JLabel();
        lblTanggalSelesai2 = new javax.swing.JLabel();
        lblHargaDiskon2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSetUp3 = new javax.swing.JButton();
        lblNamaEvent3 = new javax.swing.JLabel();
        lblHargaAwal3 = new javax.swing.JLabel();
        lblJumlahTicketFlashSale3 = new javax.swing.JLabel();
        lblTanggalMulai3 = new javax.swing.JLabel();
        lblTanggalSelesai3 = new javax.swing.JLabel();
        lblHargaDiskon3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnSetUp4 = new javax.swing.JButton();
        lblNamaEvent4 = new javax.swing.JLabel();
        lblHargaAwal4 = new javax.swing.JLabel();
        lblJumlahTicketFlashSale4 = new javax.swing.JLabel();
        lblTanggalMulai4 = new javax.swing.JLabel();
        lblTanggalSelesai4 = new javax.swing.JLabel();
        lblHargaDiskon4 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel.setBackground(new java.awt.Color(51, 0, 51));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Add EVENT Flash Sale");

        org.jdesktop.layout.GroupLayout jPanelLayout = new org.jdesktop.layout.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelLayout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jLabel22)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(jPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel22)
                    .add(jLabel23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        btnSetUp.setBackground(new java.awt.Color(153, 102, 255));
        btnSetUp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSetUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSetUp.setText("Set Up");
        btnSetUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetUpActionPerformed(evt);
            }
        });

        lblNamaEvent.setText("Nama Event");

        lblHargaAwal.setText("Harga Awal");

        lblJumlahTicketFlashSale.setText("Jumlah");

        lblTanggalMulai.setText("\"dd-MM-yyyy\" start");

        lblTanggalSelesai.setText("\"dd-MM-yyyy\" end");

        lblHargaDiskon.setText("Harga Diskon");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(lblHargaDiskon)
                        .add(11, 11, 11)
                        .add(lblHargaAwal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(51, 51, 51)
                        .add(lblNamaEvent, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(36, 36, 36)
                .add(lblJumlahTicketFlashSale)
                .add(85, 85, 85)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblTanggalMulai, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .add(lblTanggalSelesai, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(btnSetUp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblNamaEvent)
                            .add(lblTanggalMulai))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblTanggalSelesai)
                            .add(lblHargaAwal)
                            .add(lblHargaDiskon)))
                    .add(btnSetUp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(lblJumlahTicketFlashSale)
                .add(20, 20, 20))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("EVENT Flash Sale");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Available");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel6.setText("Flash Sale Period");

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        btnSetUp1.setBackground(new java.awt.Color(153, 102, 255));
        btnSetUp1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSetUp1.setForeground(new java.awt.Color(255, 255, 255));
        btnSetUp1.setText("Set Up");
        btnSetUp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetUp1ActionPerformed(evt);
            }
        });

        lblNamaEvent1.setText("Nama Event");

        lblHargaAwal1.setText("Harga Awal");

        lblJumlahTicketFlashSale1.setText("Jumlah");

        lblTanggalMulai1.setText("\"dd-MM-yyyy\" start");

        lblTanggalSelesai1.setText("\"dd-MM-yyyy\" end");

        lblHargaDiskon1.setText("Harga Diskon");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(lblHargaDiskon1)
                        .add(11, 11, 11)
                        .add(lblHargaAwal1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                        .add(51, 51, 51)
                        .add(lblNamaEvent1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(36, 36, 36)
                .add(lblJumlahTicketFlashSale1)
                .add(85, 85, 85)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblTanggalMulai1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .add(lblTanggalSelesai1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(btnSetUp1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblNamaEvent1)
                            .add(lblTanggalMulai1))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblTanggalSelesai1)
                            .add(lblHargaAwal1)
                            .add(lblHargaDiskon1)))
                    .add(btnSetUp1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(lblJumlahTicketFlashSale1)
                .add(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));

        btnSetUp2.setBackground(new java.awt.Color(153, 102, 255));
        btnSetUp2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSetUp2.setForeground(new java.awt.Color(255, 255, 255));
        btnSetUp2.setText("Set Up");
        btnSetUp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetUp2ActionPerformed(evt);
            }
        });

        lblNamaEvent2.setText("Nama Event");

        lblHargaAwal2.setText("Harga Awal");

        lblJumlahTicketFlashSale2.setText("Jumlah");

        lblTanggalMulai2.setText("\"dd-MM-yyyy\" start");

        lblTanggalSelesai2.setText("\"dd-MM-yyyy\" end");

        lblHargaDiskon2.setText("Harga Diskon");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(lblHargaDiskon2)
                        .add(11, 11, 11)
                        .add(lblHargaAwal2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                        .add(51, 51, 51)
                        .add(lblNamaEvent2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(36, 36, 36)
                .add(lblJumlahTicketFlashSale2)
                .add(85, 85, 85)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblTanggalMulai2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .add(lblTanggalSelesai2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(btnSetUp2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblNamaEvent2)
                            .add(lblTanggalMulai2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblTanggalSelesai2)
                            .add(lblHargaAwal2)
                            .add(lblHargaDiskon2)))
                    .add(btnSetUp2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(lblJumlahTicketFlashSale2)
                .add(20, 20, 20))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));

        btnSetUp3.setBackground(new java.awt.Color(153, 102, 255));
        btnSetUp3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSetUp3.setForeground(new java.awt.Color(255, 255, 255));
        btnSetUp3.setText("Set Up");
        btnSetUp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetUp3ActionPerformed(evt);
            }
        });

        lblNamaEvent3.setText("Nama Event");

        lblHargaAwal3.setText("Harga Awal");

        lblJumlahTicketFlashSale3.setText("Jumlah");

        lblTanggalMulai3.setText("\"dd-MM-yyyy\" start");

        lblTanggalSelesai3.setText("\"dd-MM-yyyy\" end");

        lblHargaDiskon3.setText("Harga Diskon");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(lblHargaDiskon3)
                        .add(11, 11, 11)
                        .add(lblHargaAwal3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                        .add(51, 51, 51)
                        .add(lblNamaEvent3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(36, 36, 36)
                .add(lblJumlahTicketFlashSale3)
                .add(85, 85, 85)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblTanggalMulai3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .add(lblTanggalSelesai3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(btnSetUp3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblNamaEvent3)
                            .add(lblTanggalMulai3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblTanggalSelesai3)
                            .add(lblHargaAwal3)
                            .add(lblHargaDiskon3)))
                    .add(btnSetUp3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(lblJumlahTicketFlashSale3)
                .add(20, 20, 20))
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 255));

        btnSetUp4.setBackground(new java.awt.Color(153, 102, 255));
        btnSetUp4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnSetUp4.setForeground(new java.awt.Color(255, 255, 255));
        btnSetUp4.setText("Set Up");
        btnSetUp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetUp4ActionPerformed(evt);
            }
        });

        lblNamaEvent4.setText("Nama Event");

        lblHargaAwal4.setText("Harga Awal");

        lblJumlahTicketFlashSale4.setText("Jumlah");

        lblTanggalMulai4.setText("\"dd-MM-yyyy\" start");

        lblTanggalSelesai4.setText("\"dd-MM-yyyy\" end");

        lblHargaDiskon4.setText("Harga Diskon");

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(50, 50, 50)
                        .add(lblHargaDiskon4)
                        .add(11, 11, 11)
                        .add(lblHargaAwal4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 65, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                        .add(51, 51, 51)
                        .add(lblNamaEvent4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 147, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(36, 36, 36)
                .add(lblJumlahTicketFlashSale4)
                .add(85, 85, 85)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(lblTanggalMulai4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .add(lblTanggalSelesai4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(btnSetUp4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .add(9, 9, 9)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel5Layout.createSequentialGroup()
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblNamaEvent4)
                            .add(lblTanggalMulai4))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblTanggalSelesai4)
                            .add(lblHargaAwal4)
                            .add(lblHargaDiskon4)))
                    .add(btnSetUp4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(lblJumlahTicketFlashSale4)
                .add(20, 20, 20))
        );

        btnNext.setText("Next");
        btnNext.setPreferredSize(new java.awt.Dimension(70, 35));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(54, 54, 54)
                .add(jLabel4)
                .add(87, 87, 87)
                .add(jLabel5)
                .add(79, 79, 79)
                .add(jLabel6)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel2)
                .add(18, 18, 18)
                .add(btnNext, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(270, 270, 270))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jLabel5)
                    .add(jLabel6))
                .add(11, 11, 11)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnNext, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel2))
                .add(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSetUpActionPerformed

    private void btnSetUp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetUp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSetUp1ActionPerformed

    private void btnSetUp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetUp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSetUp2ActionPerformed

    private void btnSetUp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetUp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSetUp3ActionPerformed

    private void btnSetUp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetUp4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSetUp4ActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        int currentValue = Integer.parseInt(jLabel21.getText());

        int totalPage = (int) Math.ceil(listOfEvent.size() / 3.0);
        if (currentValue < totalPage) {
            jLabel21.setText(String.valueOf(currentValue + 1));

            int page = Integer.parseInt(jLabel21.getText());
            showIndexFrom = 3 * page - 3;

            refreshTicketsUI();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSellerFlashSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSellerFlashSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSellerFlashSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSellerFlashSale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSellerFlashSale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSetUp;
    private javax.swing.JButton btnSetUp1;
    private javax.swing.JButton btnSetUp2;
    private javax.swing.JButton btnSetUp3;
    private javax.swing.JButton btnSetUp4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblHargaAwal;
    private javax.swing.JLabel lblHargaAwal1;
    private javax.swing.JLabel lblHargaAwal2;
    private javax.swing.JLabel lblHargaAwal3;
    private javax.swing.JLabel lblHargaAwal4;
    private javax.swing.JLabel lblHargaDiskon;
    private javax.swing.JLabel lblHargaDiskon1;
    private javax.swing.JLabel lblHargaDiskon2;
    private javax.swing.JLabel lblHargaDiskon3;
    private javax.swing.JLabel lblHargaDiskon4;
    private javax.swing.JLabel lblJumlahTicketFlashSale;
    private javax.swing.JLabel lblJumlahTicketFlashSale1;
    private javax.swing.JLabel lblJumlahTicketFlashSale2;
    private javax.swing.JLabel lblJumlahTicketFlashSale3;
    private javax.swing.JLabel lblJumlahTicketFlashSale4;
    private javax.swing.JLabel lblNamaEvent;
    private javax.swing.JLabel lblNamaEvent1;
    private javax.swing.JLabel lblNamaEvent2;
    private javax.swing.JLabel lblNamaEvent3;
    private javax.swing.JLabel lblNamaEvent4;
    private javax.swing.JLabel lblTanggalMulai;
    private javax.swing.JLabel lblTanggalMulai1;
    private javax.swing.JLabel lblTanggalMulai2;
    private javax.swing.JLabel lblTanggalMulai3;
    private javax.swing.JLabel lblTanggalMulai4;
    private javax.swing.JLabel lblTanggalSelesai;
    private javax.swing.JLabel lblTanggalSelesai1;
    private javax.swing.JLabel lblTanggalSelesai2;
    private javax.swing.JLabel lblTanggalSelesai3;
    private javax.swing.JLabel lblTanggalSelesai4;
    // End of variables declaration//GEN-END:variables
}
